# Generated by Django 4.1.5 on 2023-12-01 22:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user_accounts.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mountainsdir', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('id_str', models.CharField(default=uuid.uuid4, max_length=64)),
                ('image', models.ImageField(blank=True, upload_to='post_images')),
                ('caption', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('mountain_name', models.TextField(blank=True)),
                ('date_climbed', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('mountain_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='mountainsdir.mountain')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='userProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField()),
                ('bio', models.TextField(blank=True)),
                ('profileimg', models.ImageField(default='default_profile_photo.jpg', upload_to=user_accounts.models.profile_pictures_ids)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('town_city', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StripeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(blank=True, default=False, max_length=255, null=True)),
                ('stripe_subscription_id', models.CharField(blank=True, default=False, max_length=255, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('price', models.FloatField(blank=True, default=0.0, null=True)),
                ('stripe_price_id', models.CharField(blank=True, default=False, max_length=255, null=True)),
                ('plan', models.CharField(blank=True, default=False, max_length=15, null=True)),
                ('stripe_product', models.CharField(blank=True, default=False, max_length=255, null=True)),
                ('recurring_interval', models.CharField(blank=True, default=False, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('end_date_of_subscription', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=user_accounts.models.picture_ids)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_accounts.journalentry')),
            ],
        ),
    ]


