# Generated by Django 4.1.5 on 2023-04-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mountain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('county', models.CharField(max_length=255)),
                ('classification_orig', models.CharField(max_length=255)),
                ('classification', models.CharField(max_length=255)),
                ('height_meters', models.FloatField(default=0)),
                ('height_feet', models.FloatField(default=0)),
                ('grid_ref', models.CharField(max_length=255)),
                ('feature', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('country_abbr', models.CharField(max_length=255)),
                ('ascend_count', models.IntegerField(default=0)),
            ],
        ),
    ]
